### PR TITLE
Feature fox

### PR DESCRIPTION
**Pull request by yuchih**
@shihyi @futureappworker Please check this function and merge into master

- [x] line1
- [x] line2
- [x] fix line 1

### CODE REVIEW

**Comment by futureappworker** [comment]
line2 and fix line 1 ok!

**Comment by shihyi** [comment]
@yuchih Already checked.

**Comment by shihyi** [comment]
@yuchih already check.

**Comment by yuchih** [comment]
- [*] 1
- [*] 2
- [*] 3

@futureappworker merge pull request into master

**Pull request merged**
